bench/good: changed the naming convention.

diff --git a/bench/good/Makefile b/bench/good/Makefile
--- a/bench/good/Makefile
+++ b/bench/good/Makefile
@@ -17,7 +17,7 @@ CAMLC           := $(shell if ocamlfind ocamlc -v >/dev/null 2>&1 ; \
 # Some tests involve several input files. The naming convention for
 # these tests is /name/-[1-9].mly.
 TESTS=$(shell ls | egrep '*([1]|[^2-9]).mly')
-RESULTS=$(TESTS:.mly=.result)
+RESULTS=$(TESTS:.mly=.opp.out)
 
 test: clean $(RESULTS)
 	@ if test -e warnings; then \
@@ -30,12 +30,12 @@ test: clean $(RESULTS)
 	  exit 1; \
 	fi
 
-# The file %.result   stores the output of menhir --only-preprocess.
-# The file %.expected stores its expected output.
+# The file %.opp.out   stores the output of menhir --only-preprocess.
+# The file %.opp.exp stores its expected output.
 # The file %.out      stores the output of menhir.
 # The file %.exp      stores its expected output.
 
-%.result: %.mly
+%.opp.out: %.mly
 	@ if echo $< | grep -e "-1.mly" &> /dev/null; then		\
 	  export BASE=`echo $< | sed s/"-1.mly"/""/`;			\
 	  export FILES=`echo $$BASE-[1-9].mly`;				\
@@ -47,10 +47,10 @@ test: clean $(RESULTS)
 	fi;								\
 	$(SHELL) -c '$(MENHIR) --only-preprocess $$CMD >& $@';		\
 	if [ x$$CREATE_EXPECTED == x"1" ]; then				\
-	  cp $@ $*.expected;						\
+	  cp $@ $*.opp.exp;						\
 	fi;								\
-	if test -e $*.expected; then					\
-	  if diff $@ $*.expected >& /dev/null; then			\
+	if test -e $*.opp.exp; then					\
+	  if diff $@ $*.opp.exp >& /dev/null; then			\
 	    if $(MENHIR) --explain $$CMD >& $*.out; then		\
 	      if [ x$$CREATE_EXPECTED == x"1" ]; then			\
 		cp $*.out $*.exp;					\
@@ -82,23 +82,23 @@ test: clean $(RESULTS)
 	  else (							\
 	    echo "-> [KO] $$FILES:";					\
 	    echo "   menhir --only-preprocess produced wrong output."; 	\
-	    echo "   diff $*.expected $@";				\
+	    echo "   diff $*.opp.exp $@";				\
 	  ) | tee -a failures;						\
 	  fi;								\
 	else								\
-	  echo "Warning: missing file: $*.expected" | tee -a warnings; 	\
+	  echo "Warning: missing file: $*.opp.exp" | tee -a warnings; 	\
 	fi;								\
 
 expected:
-	@ echo "Are you sure ? (this will erase *.expected) [Press ENTER]"
+	@ echo "Are you sure ? (this will erase *.exp) [Press ENTER]"
 	@ read
 	@ mkdir -p /tmp/menhir-expected
-	@ cp *.expected /tmp/menhir-expected >& /dev/null || true
+	@ cp *.exp /tmp/menhir-expected >& /dev/null || true
 	@ CREATE_EXPECTED=1 $(MAKE) -s test
 	@ echo "Expected output re-generated."
 
 clean:
 	rm -f *~
 	rm -f *.ml *.mli *.conflicts *.automaton
-	rm -f *.result *.out failures warnings
+	rm -f *.out failures warnings
 
